name: Deployment Pipeline

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - main

jobs: 
  skip_redundant_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

  code-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
    
  unit_testing:
    needs: [code-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Unit Test
        run: npm run test

  e2e_testing:
    needs: [code-lint]
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Cypress Run
        uses: cypress-io/github-action@v5.0.5
        with: 
          browser: electron
          spec: cypress/e2e/app.cy.js
          start: npm run start
          wait-on: http://127.0.0.1:8080