name: Deployment Pipeline

on:
  push:
    branches:
      - test-ts

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: Unit Test
        run: npm run test
      - name: Cypress Run
        uses: cypress-io/github-action@v5.0.5
        with: 
          browser: electron
          spec: cypress/e2e/app.cy.js